CREATE DATABASE TAREA5

USE TAREA5

--PAGO DE COLEGIATURA
CREATE TABLE ALUMNO(
NOCONTROL INT PRIMARY KEY,
NOMBRE VARCHAR(40),
RECIBO FLOAT,
CORREO NVARCHAR(60),
SEMESTRE INT,
FECHADEVENCIMIENTO DATETIME,
)
--INSERTAR VALORES
INSERT INTO ALUMNO VALUES(20210575, 'Anthony Guillen Martinez', 1800, 'anthony.guillen201@tectijuana.edu.mx', 6, '06-09-2022' )

--MOSTRAR TABLA
SELECT*FROM ALUMNO